[project]
name = "ml-inference-orchestration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RYashaswini", email = "r.yashaswini94@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ml-inference-orchestration = "ml_inference_orchestration:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
