apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-orchestration
  labels:
    app: ml-inference-orchestration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-inference-orchestration
  template:
    metadata:
      labels:
        app: ml-inference-orchestration
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ml-inference-orchestration
          image: ghcr.io/ryashaswini/ml-inference-orchestration:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"